### ISSUE TITLE
Deposit Failure: TypeError - T.readBigUInt64LE is not a function #8

### ISSUE THREAD

**Issue by Adil7767** [OrderlyNetwork/js-sdk#8]
I am trying to deposit using this code
```

import { useDeposit } from "@orderly.network/hooks";

const {
    balance,
    allowance,
    approve,
    deposit,
    quantity,
    setQuantity,
    depositFee,
    depositFeeRevalidating,
    balanceRevalidating
  } = useDeposit({
    address: token?.address,
    decimals: token?.decimals,
    srcToken: token?.symbol,
    // srcChainId: hexToNumber(selectedNetwork.networkId),
    srcChainId: Number(account.chainId),
  });

onst handleDeposit = async () => {
    if (!quantity || inputError) return;

    setIsDepositing(true);
    const { update } = customNotification({
      eventCode: "deposit",
      type: "pending",
      message: "Depositing USDC...",
    });

    try {
      await deposit();
      update({
        eventCode: "depositSuccess",
        type: "success",
        message: "Deposit successful!",
        autoDismiss: 5000,
      });
      setQuantity("");
    } catch (err) {
      console.error("Deposit failed:", err);
      update({
        eventCode: "depositError",
        type: "error",
        message: "Deposit failed or was rejected",
        autoDismiss: 5000,
      });
    } finally {
      setIsDepositing(false);
    }
  };

```
The deposit function is failing due to the following TypeError:
```

DepositContent.tsx:265 Deposit failed: TypeError: T.readBigUInt64LE is not a function
    at chunk-XBVNYGUZ.js?v=94200d98:56683:26
    at Generator.next (<anonymous>)
    at t (chunk-XBVNYGUZ.js?v=94200d98:56523:12)

```

**Comment by Tarnadas** [comment]
Hey,
I remember seeing this bug and this is not an issue within the SDK. It is a bundler issue. The bundler incorrectly polyfills Nodejs' Buffer

**Comment by Adil7767** [comment]
The issue is resolved after updating 2 to 3 things, like  updating polyfils file and add one code block in that file where it causing issue
